# Generated by Django 5.1.1 on 2024-10-15 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('tipoDeContenido', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('autor', models.ForeignKey(default='Autor borrado', on_delete=django.db.models.deletion.SET_DEFAULT, to='route.autor')),
                ('contenidosPrevios', models.ManyToManyField(to='route.contenido')),
                ('tags', models.ManyToManyField(default='Tag borrado', to='route.tag')),
            ],
        ),
        migrations.CreateModel(
            name='rutaAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('completado', models.BooleanField(default=False)),
                ('contenidos', models.ManyToManyField(related_name='rutas', to='route.contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
