# Generated by Django 4.2.5 on 2024-09-11 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish')], default='ES', max_length=50)),
                ('learning_style', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('curso', 'Curso'), ('audio', 'Audio')], default='text', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
