# Generated by Django 4.2.5 on 2024-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_learningpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEducacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('descripcion_corta', models.CharField(blank=True, max_length=500)),
                ('tipo_recurso', models.CharField(choices=[('video', 'Video'), ('texto', 'Texto'), ('audio', 'Audio')], default='video', max_length=5)),
                ('duracion', models.PositiveIntegerField()),
            ],
        ),
    ]
