# Generated by Django 5.1.1 on 2024-10-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_learningpreferences_tipo_interes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenidoEducacion',
        ),
        migrations.DeleteModel(
            name='LearningPreferences',
        ),
    ]
