# Generated by Django 5.1.1 on 2024-10-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_delete_contenidoeducacion_delete_learningpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='contenidosPrevios',
            field=models.ManyToManyField(null=True, to='route.contenido'),
        ),
    ]
