# Generated by Django 5.1.1 on 2024-10-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_alter_contenido_contenidosprevios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='contenidosPrevios',
            field=models.ManyToManyField(blank=True, to='route.contenido'),
        ),
    ]
