# Generated by Django 5.1.1 on 2024-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_favorito_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='imagen',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='contenidos/img/'),
        ),
    ]
