# Generated by Django 5.1.1 on 2024-10-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_alter_contenido_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='IdContenido',
            new_name='idContenido',
        ),
    ]
