# Generated by Django 5.1.1 on 2024-11-06 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0016_alter_reporte_descripcion_alter_reporte_idcontenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresocontenido',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
