# Generated by Django 4.2.5 on 2024-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0017_progresocontenido_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='tipoDeContenido',
            field=models.IntegerField(choices=[(1, 'Video'), (2, 'Texto'), (3, 'Audio')]),
        ),
    ]
