# Generated by Django 5.1.1 on 2024-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0017_progresocontenido_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Introductorio'), (2, 'Principiante-Básico'), (3, 'Principiante-Intermedio'), (4, 'Intermedio'), (5, 'Intermedio-Avanzado'), (6, 'Avanzado'), (7, 'Muy Avanzado'), (8, 'Experto')], default=3),
            preserve_default=False,
        ),
    ]
