# Generated by Django 4.1 on 2024-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0018_contenido_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='IntelligenceWay/static/contenidos/img/'),
        ),
    ]
