# Generated by Django 5.1.1 on 2024-10-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
