# Generated by Django 5.1.1 on 2024-10-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='tiempo',
            field=models.IntegerField(default=1),
        ),
    ]
