# Generated by Django 5.1.1 on 2024-10-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_content_user_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferenciaAudio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferenciaTexto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferenciaVideo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tiempoAprendizaje',
            field=models.IntegerField(null=True),
        ),
    ]
