# Generated by Django 5.1.1 on 2024-10-14 05:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formularioAprendizajeUsuario',
            new_name='ModeloAprendizajeUsuario',
        ),
    ]
